name: 'LLVM Embedded Toolchain for Arm'
description: 'Install and set up the LLVM Embedded Toolchain for Arm (clang).'
author: 'Katherine Whitlock'
inputs:
  release:
    description: 'LLVM Embedded Toolchain for Arm release name (e.g. "16.0.0").'
    default: 'latest'
    required: false
  path-env-var:
    description: 'Name for an environmental variable to be created with the toolchain /bin path (for executables).'
    required: false
  toolchain-env-var:
    description: 'Name for an environmental variable to be created with the toolchain path.'
    required: false    
outputs:
  path:
    description: 'Path to the bin folder with the toolchain executables.'
  toolchain:
    description: 'Path to the main toolchain folder'
runs:
  using: 'node16'
  pre-if: runner.os == 'linux'
  pre: 'setup.js'
  main: 'dist/index.js'
branding:
  icon: 'cpu'
  color: 'gray-dark'
