name: Check file download URLs

on:
  schedule:
    # Runs every day at 19:30
    - cron: '30 19 * * *'

jobs:
  # Test and check build errors
  test-build:
    name: Check file URLs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm run test:urls
